name: Deploy to Cpanel via FTP

on:
  push:
    branches:
      - main  # Ganti dengan nama branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Direktori lokal yang akan di-upload
          git-ftp-args: --insecure  # Optional, jika Anda menggunakan FTP yang tidak menggunakan SSL
          exclude: ".git,.github"  # Direktori atau file yang akan dikecualikan
